routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use Moodhu\Repositories\AccommodationRepository;
use Moodhu\Repositories\SpecialOfferRepository;
use Moodhu\Repositories\TourRepository;
use Illuminate\Http\Request;

require_once __DIR__.'/../ITravel/iTravelAPI.php';
Route::get('/', ['role'=>'*', function () {
    return view('welcome');
}]);


Route::get('/customized', function(Request $request, AccommodationRepository $repository) {
    $filters = $request->all();

    $params = [];

    if ($request->has('current_page')) {
        $params['CurrentPage'] = $request['current_page'];
    }
    if ($request->has('from_date')) {
        $params['StartDate'] = \Carbon\Carbon::parse($request->get('from_date'))->getTimestamp();
        $params['EndDate'] = \Carbon\Carbon::parse($request->get('to_date'))->getTimestamp();
    }

    if ($request->has('name'))
    {
        $params['ObjectAttributeFilterList']['AttributeFilter'] = [
            [
                'AttributeID' => 121,
                'AttributeValue' => $request->get('name'),
                'ComparisonType' => 'Like'
            ]
        ];
    }
    if($request->has('number_of_adults'))
    {
        $params['UnitAttributeFilterList']['AttributeFilter'] = [
            [
                'AttributeID' => 120,
                'AttributeValue' => $request->get('number_of_adults'),
                'ComparisonType' => 'GreaterOrEqualThan'
            ]
        ];

    }

    if($request->has('number_of_children'))
    {
        $params['children'] = $request->get('number_of_children');
    }

    if($request->has('category_id'))
    {
        $params['categoryID'] = $request->get('category_id');
    }

    $data = [
        'data' => []
    ];

    $request->session()->flush('message');

    try
    {
        $data = $repository->paginate($params);

    }
    catch (Exception $e)
    {
        $request->session()->flash("message", $e->getMessage());
    }



	return view('customized', array_merge($filters,['data'=>$data, 'filters' => $filters]));
});

Route::get('/destinations', function()
{
	$s = new \GetAllDestinations();
	dd ($s->GetAllDestinations()->GetAllDestinationsResult);
});

Route::get('/test', function()
{
	$s = new \GetSearchResults();
	$SearchResults = $s->GetSearchResults();
	$results =  $SearchResults->GetSearchResultsResult->AccommodationObjectList->AccommodationObject;

	dd($SearchResults);

	return $s->GetJSON();

	$response = [];

	if(count($results) > 0)
	{
		foreach ($results as $item) {

			
			$response[] = formatResponse($item);// $hotel;

			

		}
	}

	// return [];
	return $response;
	// return view('mails.correction_approved', [ 'model' => \App\Correction::first()]);
});

Route::get('/inquiry/{id}', ['as'=>'book', function($id)
{
    $start = (\Carbon\Carbon::now()->timestamp* 10000000) + 621355968000000000;
    $end = (\Carbon\Carbon::now()->timestamp* 10000000) + 621355968000000000;

    $persons = '';

    if(request()->has('from_date'))
    {
        $start = (\Carbon\Carbon::parse(request()->get('from_date'))->timestamp * 10000000) + 621355968000000000;
    }

    if(request()->has('to_date'))
    {
        $end = (\Carbon\Carbon::parse(request()->get('to_date'))->timestamp * 10000000) + 621355968000000000;
    }


    if(request()->has('number_of_rooms') && request()->has('number_of_adults'))
    {
        $no_of_peeps_per_room = request()->has('number_of_adults') / request()->has('number_of_rooms');
        
        $persons = (\Carbon\Carbon::parse(request()->get('to_date'))->timestamp * 10000000) + 621355968000000000;
    }

    

	return view('book',['UnitID'=>$id, 'start' => $start, 'end' => $end]);
}]);

Route::get('/accommodation/{id}', function(AccommodationRepository $repository, $id)
{
	$model = $repository->getDetails($id);
	return view('details.accommodation', compact('model'));
});

Route::get('/tour/{id}', function(TourRepository $repository, $id)
{
	$model = $repository->getDetails($id);
	return view('details.tour', compact('model'));
});




Route::get('/terms_and_conditions', function()
{
    return view('terms_and_conditions');
});

Route::get('/like_and_win', function()
{
    return view('like_and_win');
});


Route::post('/like_and_win', function(\Moodhu\Repositories\CustomerRepository $repository)
{

    request()->flash();
    $client = new GuzzleHttp\Client();
    $res = $client->post('https://www.google.com/recaptcha/api/siteverify',
        ['form_params' =>  [
            'secret' => '6Ldb-xsUAAAAAC7sdGglhqlFHaS_427_HpiOU7as',
            'response' => request()->get('g-recaptcha-response'),
            'remoteip' => request()->ip()
        ]]
    );
    $item =  \GuzzleHttp\json_decode($res->getBody());

    if($item->success)
    {
        if($repository->createCustomer(request()->all()))
        {
            return view('liked');
        }
        else
        {
            request()->session()->flash("exists", "A customer exists with the details you have provided.");

        }
    }
    else
    {
        request()->session()->flash("error", "Need the human verification done!");
    }

    return view('like_and_win')->withInput(request()->all());
});

//


Route::get('/privacy_policy', function()
{
    return view('privacy_policy');
});


Auth::routes();

Route::group(['prefix'=>'tools'], function()
{
    Route::get('/customer', function(\Moodhu\Repositories\CustomerRepository $rep)
    {
        $countries = app('api')->GetAllCountries([
            'getAllCountriesParameter' => [ 'SearchQuery' => 's' ]
        ])->GetAllCountriesResult->CountryList;


        foreach ($countries as $country) {
            dd($country,0);
        }

        dd();
        $cus = new CustomerInsert();
        dd($cus->InsertCustomer(), $rep->createCustomer(['name' => 'Yameen','mobile_number' => '9696470','country_id' => 54]));
//        dd();
    });
});


Route::get('/page/{slug}', [ 'as' => 'page', 'uses' => 'PageController@page']);
Route::any('/register','HomeController@index');


Route::group(['prefix'=>'admin'], function()
{
    // Auth::routes();
    Route::get('/login', 'Auth\LoginController@showLoginForm' );
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/logout', 'Auth\LoginController@logout');

    Route::group(['middleware'=>'auth'], function()
    {
        Route::get('/pages/{pages}/destroy/confirm',['as'=>'pages.confirm','uses'=>'PageController@confirm']);
        Route::resource('/pages','PageController',['only' => ['index', 'show', 'create', 'store','edit', 'update', 'destroy','confirm']]);
        Route::get('/navigations/{navigations}/destroy/confirm',['as'=>'navigations.confirm','uses'=>'NavigationController@confirm']);
        Route::resource('/navigations','NavigationController',['only' => ['index', 'show', 'create', 'store','edit', 'update', 'destroy','confirm']]);


        // Route::get('login' , 'Auth\AuthController@getLogin' ) ;
        // Route::post('registrar', 'Auth\AuthController@postLogin') ;
        Route::get('/', function()
        {
            return view('home');
        });

    });

    Route::get('/norole', function()
    {
        return view('auth.norole');
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/admin.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/admin/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->

                    <ul class="nav navbar-nav">
                    @if (!Auth::guest())
                        <li>
                            <a href="{{ route('pages.index') }}">Pages</a>
                        </li>
                        <li>
                            <a href="{{ route('navigations.index') }}">Menus</a>
                        </li>
                    @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/admin/login') }}">Login</a></li>
                            <!-- <li><a href="{{ url('/admin/register') }}">Register</a></li> -->
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
        	@yield('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="/js/admin.js"></script>
     @yield('scripts')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>Moodhu Holidays</title>

	<!-- Styles -->
	<link href="/css/all.css" rel="stylesheet">
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
	<style type="text/css">
		.h1000
		{
			height: calc(100vh - 60px);
		}

		@media only screen and (max-width: 601px)
		{
			.carousel .carousel-item img
			{
				height: 100%;
				width: auto;
			}
		}
		.carousel .carousel-item img
		{
			height: 100%;
			min-width: 100%;
		}
		img.activator{
			width: 100%;
		}
	</style>
	<!-- Scripts -->
	<script>
		window.Laravel = <?php echo json_encode([
			'csrfToken' => csrf_token(),
			]); ?>
		</script>
		<!-- CSS  -->
		
	</head>
	<body ng-app='app'>
		<main>
			@include('partials.header')
			@yield('content')
		</main>

		@include('partials.footer')


		<!-- Scripts -->
		<script src="/js/all.js"></script>
		<script type="text/javascript">


			app.controller('bookingController', function($scope, $http, $location, $filter)
			{
				$scope.destinations = [];
                $scope.loading = false;
                $scope.filter_loading = true;

				$scope.minDate = true;

				$scope.getMinDate = function()
				{
					console.log('Date changed', $filter('date')($scope.booking.from_date, 'yyyy-MM-dd'));
					return $filter('date')($scope.booking.from_date, 'yyyy-MM-dd');
				}

				$scope.change = function(selected)
				{
					$scope.toDate = selected.obj;
				}

				$scope.filters = {};

				$scope.booking = {
                    destinations: [],
                    currentPage: 1,
                    children_age_groups: []
                };


                $scope.$watch('booking.number_of_children', function()
                {
					$scope.booking.children_age_groups = [];
					for (var i = $scope.booking.number_of_children - 1; i >= 0; i--) {
						$scope.booking.children_age_groups.push({age: null});
					}
                });

                $scope.toggle = function (id) {
                    if ($scope.booking.destinations.indexOf(id) === -1) {
                        $scope.booking.destinations.push(id);
                    } else {
                        $scope.booking.destinations.splice($scope.booking.destinations.indexOf(id), 1);
                    }
                };

    //             $scope.load = function(page)
    //             {
    //                 $scope.booking.current_page = page;
    //                 $scope.search();
    //             }

				// $http.get('/api/filters').success(function($filters)
				// {
    //                 $scope.filter_loading = false;
    //                 $scope.filters = $filters;
				// });

				

				$scope.submit = function()
				{
					$('form').submit();
					$scope.loading = true;

					// $http.post('/api/customize', $scope.booking).success(function(data)
					// {
					// 	$scope.destinations = data;
					// 	$scope.loading = false;

					// }).error(function()
					// {
					// 	$scope.loading = false;
					// });
					$location.path(jsonToQueryString($scope.booking));


//
				}

			});

			app.controller('specialOffer', function($scope, $http){
				$scope.special_offers = [];
				$scope.loading = true;

				$http.get('/api/special-offers?pageSize=9').success(function($data)
				{	
					$scope.special_offers = $data;
				});
			}).controller('tours', function($scope, $http){
				$scope.tours = [];
				$scope.loading = true;

				$http.get('/api/tours?pageSize=9').success(function($data)
				{	
					$scope.tours = $data;
				});
			}).controller('accommodations', function($scope, $http, $location){
				$scope.accommodations = [];
				$scope.loading = true;
				$scope.page = $location.search().current_page || 1;
				$scope.page_size = $location.search().page_size || 18;
				$scope.loading = false;


				$scope.loadPage = function($page)
				{
					$scope.loading = true;
					$http.get('/api/accommodations?page-size='+$scope.page_size+'&current-page='+ $page + '&raw=false').success(function($data)
					{
						$scope.loading = false;

						$scope.accommodations = $data;
						$scope.total = $data.total;
						$scope.lastPage = $data.lastPage;

						$location.search('current_page', $page);

					}).error(function()
					{
						$scope.loading = false;

					});

				};

				$scope.loadPage($scope.page);
			});


			(function($){
				$(function(){
					$('.button-collapse').sideNav();
					$('.parallax').parallax();
					$('.carousel.carousel-slider').carousel({full_width: true});

					$('.carousel').carousel({
					    padding: 200    
					});
					autoplay()   
					function autoplay() {
					    $('.carousel').carousel('next');
					    setTimeout(autoplay, 4500);
					}

				}); // end of document ready
				$(function() {
					$('a[href*="#"]:not([href="#"])').click(function() {
					if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
						var target = $(this.hash);
						target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
						if (target.length) {
						$('html, body').animate({
							scrollTop: target.offset().top
						}, 1000);
						return false;
						}
					}
					});
				});
			})(jQuery);
		</script>

		@yield('scripts')

	</body>
	</html>

resources/views/layouts/detail.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/all.css" rel="stylesheet">

    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
    
    <style type="text/css">
        .h1000
        {
            height: calc(100vh - 60px);
        }
        #frmEnquire
        {
            height: auto;
            min-height: 600px;
        }
        img.activator{
            width: 100%;
        }
        .navbar-fixd {
            box-shadow: 0 0 140px #37a1d8;
        }
        .panel-body i {
            font-size: 15px;
            margin: -2px;
            vertical-align: middle;
        }

        .unitSlider
        {
            margin-top: 0 !important;
        }

        i
        {
            vertical-align: middle;
        }
        td, th {
            padding: 4px !important;
        }

        .modal-header {
            padding: 10px 10px 0;
            border-bottom: 1px solid #ccc;
        }
        a[data-slide-index] img {
            width: 30px;
            height: 30px;
            border: 0;
            margin: 0;
            padding: 1px;
        }
    </style>
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
            ]); ?>
        </script>
        <!-- CSS  -->
    </head>
    <body ng-app='app'>
        <main>
            @include('partials.header')
            @yield('content')
        
        </main>
        @include('partials.footer')




                <!-- Scripts -->
        <script src="/js/all.js"></script>
        <script type="text/javascript">
            (function($){
                $(function(){
                    $('.button-collapse').sideNav();
                    $('.parallax').parallax();
                    $('.slider').slider({full_width: true});

                }); // end of document ready
                $(function() {
                    $('a[href*="#"]:not([href="#"])').click(function() {
                    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                        var target = $(this.hash);
                        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                        if (target.length) {
                        $('html, body').animate({
                            scrollTop: target.offset().top
                        }, 1000);
                        return false;
                        }
                    }
                    });
                });
            })(jQuery); // end of jQuery name space
        </script>

        @yield('scripts')

    </body>
    </html>